# Generated by Django 5.0.2 on 2025-05-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcacao_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='marcacao_app.cliente')),
            ],
        ),
    ]
