# Generated by Django 5.0.2 on 2025-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcacao_app', '0002_arquivopdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoRequerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHAVE_REQUERIMENTOS', models.CharField(max_length=50, unique=True)),
                ('DESCRICAO', models.CharField(max_length=255)),
                ('TEXTO_REQUERIMENTOS', models.TextField()),
            ],
        ),
    ]
