# Generated by Django 5.0.2 on 2025-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcacao_app', '0003_textorequerimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textorequerimento',
            name='id',
        ),
        migrations.AlterField(
            model_name='textorequerimento',
            name='CHAVE_REQUERIMENTOS',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
