# Generated by Django 5.0.2 on 2025-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcacao_app', '0004_remove_textorequerimento_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textorequerimento',
            name='CHAVE_REQUERIMENTOS',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='textorequerimento',
            table='texto_requerimento',
        ),
    ]
